sonar.projectKey=bobbidenisleo-glitch_java-project-72
sonar.organization=bobbidenisleo-glitch

sonar.sources=app/src/main/java
sonar.tests=app/src/test/java
sonar.java.binaries=app/build/classes/java/main

sonar.sourceEncoding=UTF-8
