sonar.projectKey=bobbidenisleo-glitch_java-project-72
sonar.organization=bobbidenisleo-glitch

# Путь к исходникам (относительно корня репозитория)
sonar.sources=app/src/main/java
sonar.tests=app/src/test/java

# Кодировка
sonar.sourceEncoding=UTF-8
