@param gg.jte.Content content
@param java.lang.String flash
@param java.lang.String flashType

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">Анализатор страниц</a>
        </div>
    </nav>

    <main class="container mt-3">
      @if(flash != null && !flash.isEmpty())
    <div class="alert alert-${flashType}" role="alert">
        ${flash}
    </div>
@endif
  ${content}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
